- name: variables from the files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks: 
    - name: print the varaible
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Topics are {{ TOPICS }}"