- name: Course Information
  hosts: local
  connection: local
  vars:
    course_name: "ABC" # string
    duration: 10 #number
    topics: # list, [] this means list
    - linux
    - shell
    - ansible
    - AWS
    live: true # boolean
    tools: #map, {} this means map
      ci: jenkins
      cloud: aws
      containerization: docker
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ course_name }}, duration: {{ duration }}, topics are: {{ topics }}, is it live?: {{ live }}, tools covered are: {{ tools }}"