- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0ea509ad4cba242d7
    sg_id: sg-0e978039cdb6c3057
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    zone: daws82s.online
    instances:
    - mysql
    - backend
    - frontend